name: deploy

on:
  push:
    branches: [ main ]

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
  
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' 
    
    - name: Deploy
      uses: deployphp/action@v1
      with:
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        vendor/bin/deployer.phar: deployer
        

env:
    hosts: 202.123.248.7
    remote_user: shafiq
    deploy_path: '~/example-app1'

    build:
    - cd: '{{release_path}}'
    - run: 'npm run build'

deploy:failed deploy:unlock
