name: deploy

on:
  push:
    branches: [ main ]

concurrency: production_environment

jobs:
    deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
  
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' 
    
    - name: Deploy
      uses: deployphp/action@v1
      with:
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        vendor/bin/deployer.phar: deployer
      
    - name: Deploy to Production
      env:
      DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
    run: php vendor/bin/dep deploy prod --branch="main" -vv
    
    - name: Install Composer dependencies
    run: composer install --no-interaction --no-progress --prefer-dist

    build:
      cd: '{{release_path}}'
      run: |
    npm install
    npm run build
